{ \
+filter{an-v3-lib} \
+filter{an-v3-kernel} \
+filter{an-v3-privoxy} \
# comment out any unwanted modules below \
+filter{an-v3-ui} \
+filter{an-v3-main} \
+filter{an-v3-layout} \
+filter{an-v3-style} \
+filter{an-v3-redesign} \
+filter{an-v3-ajax} \
}
forum\d+\.hkgolden\.com/(?:$|[a-z]+?\.(?:aspx|html))