annuus.addModules({

'f42d2599-ae79-40de-a3a2-9016097454f4':
{
	title: 'Themes',
	pages: { comp: [all] },
	tasks: {
		'd15b72b1': {
			service: 'data',
			name: 'themes',
			json: {
				"VIIV": {
					"cornerRadius":"0px",
					"borderColorHeader":"fff",
					"bgColorHeader":"000",
					"fcHeader":"fff",
					"borderColorContent":"000",
					"bgColorContent":"fafafa",
					"fcContent":"000",
					"borderColorDefault":"000",
					"bgColorDefault":"fff",
					"fcDefault":"000",
					"borderColorHover":"000",
					"bgColorHover":"fff",
					"fcHover":"555",
					"borderColorActive":"000",
					"bgColorActive":"fff",
					"fcActive":"555",
					"borderColorHighlight":"000",
					"bgColorHighlight":"eee",
					"fcHighlight":"000",
					"borderColorError":"000",
					"bgColorError":"555",
					"fcError":"fff",
					"bgColorOverlay":"fff",
					"bgColorShadow":"fff",

					"fcAnchorLink":"000",
					"fcAnchorVisited":"555",
					"fcAnchorHover":"555",

					"bgColorContent2":"fff",
					"fcContent2":"000",
					"fcTime":"000",
					"fcQuote":"000",

					"uriHKGLogo":"/images/index_images/blacklogo.jpg"
				},

				"HKGolden": {
					"cornerRadius":"0px",
					"borderColorHeader":"6ea0c4",
					"bgColorHeader":"6ea0c4",
					"fcHeader":"ffffff",
					"borderColorContent":"cccccc",
					"bgColorContent":"f8f8f8",
					"fcContent":"000000",
					"borderColorDefault":"ccddea",
					"bgColorDefault":"ccddea",
					"fcDefault":"1a3448",
					"borderColorHover":"ccddea",
					"bgColorHover":"ccddea",
					"fcHover":"33aaaa",
					"borderColorActive":"ccddea",
					"bgColorActive":"ccddea",
					"fcActive":"33aaaa",
					"borderColorHighlight":"e9ec6c",
					"bgColorHighlight":"e9ec6c",
					"fcHighlight":"000000",
					"borderColorError":"cc2331",
					"bgColorError":"cc2331",
					"fcError":"ffffff",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"1a3448",
					"fcAnchorVisited":"2e5c7f",
					"fcAnchorHover":"33aaaa",

					"bgColorContent2":"ffffff",
					"fcContent2":"999999",
					"fcTime":"800000",
					"fcQuote":"0000a0"
				},

				"HKGolden 2": {
					"cornerRadius":"0px",
					"borderColorHeader":"6ea0c4",
					"bgColorHeader":"6ea0c4",
					"fcHeader":"ffffff",
					"borderColorContent":"cccccc",
					"bgColorContent":"f8f8f8",
					"fcContent":"000000",
					"borderColorDefault":"c0c0c0",
					"bgColorDefault":"ffffff",
					"fcDefault":"336699",
					"borderColorHover":"99bbee",
					"bgColorHover":"99bbee",
					"fcHover":"ffffff",
					"borderColorActive":"99bbee",
					"bgColorActive":"99bbee",
					"fcActive":"ffffff",
					"borderColorHighlight":"e9ec6c",
					"bgColorHighlight":"e9ec6c",
					"fcHighlight":"000000",
					"borderColorError":"cc2331",
					"bgColorError":"cc2331",
					"fcError":"ffffff",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"336699",
					"fcAnchorVisited":"997399",
					"fcAnchorHover":"997399",

					"bgColorContent2":"ffffff",
					"fcContent2":"999999",
					"fcTime":"800000",
					"fcQuote":"0000a0"
				},

				"UI Lightness": {
					"cornerRadius":"4px",
					"borderColorHeader":"e78f08",
					"bgColorHeader":"f6a828",
					"fcHeader":"ffffff",
					"borderColorContent":"dddddd",
					"bgColorContent":"eeeeee",
					"fcContent":"333333",
					"borderColorDefault":"cccccc",
					"bgColorDefault":"f6f6f6",
					"fcDefault":"1c94c4",
					"borderColorHover":"fbcb09",
					"bgColorHover":"fdf5ce",
					"fcHover":"c77405",
					"borderColorActive":"fbd850",
					"bgColorActive":"ffffff",
					"fcActive":"eb8f00",
					"borderColorHighlight":"fed22f",
					"bgColorHighlight":"ffe45c",
					"fcHighlight":"363636",
					"borderColorError":"cd0a0a",
					"bgColorError":"b81900",
					"fcError":"ffffff",
					"bgColorOverlay":"666666",
					"bgColorShadow":"000000",

					"fcAnchorLink":"1c94c4",
					"fcAnchorVisited":"2c75b0",
					"fcAnchorHover":"c77405",

					"bgColorContent2":"ffffff",
					"fcContent2":"999999",
					"fcTime":"966a31",
					"fcQuote":"20547f"
				},

				"UI Darkness": {
					"cornerRadius":"6px",
					"borderColorHeader":"333333",
					"bgColorHeader":"333333",
					"fcHeader":"ffffff",
					"borderColorContent":"666666",
					"bgColorContent":"000000",
					"fcContent":"ffffff",
					"borderColorDefault":"666666",
					"bgColorDefault":"555555",
					"fcDefault":"eeeeee",
					"borderColorHover":"59b4d4",
					"bgColorHover":"0078a3",
					"fcHover":"ffffff",
					"borderColorActive":"ffaf0f",
					"bgColorActive":"f58400",
					"fcActive":"ffffff",
					"borderColorHighlight":"cccccc",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"2e7db2",
					"borderColorError":"ffb73d",
					"bgColorError":"ffc73d",
					"fcError":"111111",
					"bgColorOverlay":"5c5c5c",
					"bgColorShadow":"cccccc",

					"fcAnchorLink":"d4d4d4",
					"fcAnchorVisited":"8c8c8c",
					"fcAnchorHover":"8c8c8c",

					"bgColorContent2":"1a1a1a",
					"fcContent2":"999999",
					"fcTime":"f58400",
					"fcQuote":"59b4d4"
				},

				"Smoothness": {
					"cornerRadius":"4px",
					"borderColorHeader":"aaaaaa",
					"bgColorHeader":"cccccc",
					"fcHeader":"222222",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"ffffff",
					"fcContent":"222222",
					"borderColorDefault":"d3d3d3",
					"bgColorDefault":"e6e6e6",
					"fcDefault":"555555",
					"borderColorHover":"999999",
					"bgColorHover":"dadada",
					"fcHover":"212121",
					"borderColorActive":"aaaaaa",
					"bgColorActive":"ffffff",
					"fcActive":"212121",
					"borderColorHighlight":"fcefa1",
					"bgColorHighlight":"fbf9ee",
					"fcHighlight":"363636",
					"borderColorError":"cd0a0a",
					"bgColorError":"fef1ec",
					"fcError":"cd0a0a",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"555555",
					"fcAnchorVisited":"888888",
					"fcAnchorHover":"212121",

					"bgColorContent2":"eeeeee",
					"fcContent2":"999999",
					"fcTime":"404040",
					"fcQuote":"404040"
				},

				"Start": {
					"cornerRadius":"5px",
					"borderColorHeader":"4297d7",
					"bgColorHeader":"2191c0",
					"fcHeader":"eaf5f7",
					"borderColorContent":"a6c9e2",
					"bgColorContent":"fcfdfd",
					"fcContent":"222222",
					"borderColorDefault":"77d5f7",
					"bgColorDefault":"0078ae",
					"fcDefault":"ffffff",
					"borderColorHover":"448dae",
					"bgColorHover":"79c9ec",
					"fcHover":"026890",
					"borderColorActive":"acdd4a",
					"bgColorActive":"6eac2c",
					"fcActive":"ffffff",
					"borderColorHighlight":"fcd113",
					"bgColorHighlight":"f8da4e",
					"fcHighlight":"915608",
					"borderColorError":"cd0a0a",
					"bgColorError":"e14f1c",
					"fcError":"ffffff",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"999999",

					"fcAnchorLink":"0078ae",
					"fcAnchorVisited":"a582ad",
					"fcAnchorHover":"6897ad",

					"bgColorContent2":"cedfe5",
					"fcContent2":"999999",
					"fcTime":"5d9126",
					"fcQuote":"48701d"
				},

				"Redmond": {
					"cornerRadius":"5px",
					"borderColorHeader":"4297d7",
					"bgColorHeader":"5c9ccc",
					"fcHeader":"ffffff",
					"borderColorContent":"a6c9e2",
					"bgColorContent":"fcfdfd",
					"fcContent":"222222",
					"borderColorDefault":"c5dbec",
					"bgColorDefault":"dfeffc",
					"fcDefault":"2e6e9e",
					"borderColorHover":"79b7e7",
					"bgColorHover":"d0e5f5",
					"fcHover":"1d5987",
					"borderColorActive":"79b7e7",
					"bgColorActive":"f5f8f9",
					"fcActive":"e17009",
					"borderColorHighlight":"fad42e",
					"bgColorHighlight":"fbec88",
					"fcHighlight":"363636",
					"borderColorError":"cd0a0a",
					"bgColorError":"fef1ec",
					"fcError":"cd0a0a",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"2e6e9e",
					"fcAnchorVisited":"9b769e",
					"fcAnchorHover":"79b7e7",

					"bgColorContent2":"f2f5f7",
					"fcContent2":"778c8b",
					"fcTime":"bd5f7a",
					"fcQuote":"455a73"
				},

				"Sunny": {
					"cornerRadius":"8px",
					"borderColorHeader":"494437",
					"bgColorHeader":"817865",
					"fcHeader":"ffffff",
					"borderColorContent":"8e846b",
					"bgColorContent":"feeebd",
					"fcContent":"383838",
					"borderColorDefault":"d19405",
					"bgColorDefault":"fece2f",
					"fcDefault":"4c3000",
					"borderColorHover":"a45b13",
					"bgColorHover":"ffdd57",
					"fcHover":"381f00",
					"borderColorActive":"655e4e",
					"bgColorActive":"ffffff",
					"fcActive":"0074c7",
					"borderColorHighlight":"eeb420",
					"bgColorHighlight":"fff9e5",
					"fcHighlight":"1f1f1f",
					"borderColorError":"ffb73d",
					"bgColorError":"d34d17",
					"fcError":"ffffff",
					"bgColorOverlay":"5c5c5c",
					"bgColorShadow":"cccccc",

					"fcAnchorLink":"4c3000",
					"fcAnchorVisited":"4a4d3a",
					"fcAnchorHover":"1a140a",

					"bgColorContent2":"d6c89f",
					"fcContent2":"948f6c",
					"fcTime":"565e2a",
					"fcQuote":"383220"
				},

				"Overcast": {
					"cornerRadius":"6px",
					"borderColorHeader":"bbbbbb",
					"bgColorHeader":"dddddd",
					"fcHeader":"444444",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"c9c9c9",
					"fcContent":"333333",
					"borderColorDefault":"cccccc",
					"bgColorDefault":"eeeeee",
					"fcDefault":"3383bb",
					"borderColorHover":"bbbbbb",
					"bgColorHover":"f8f8f8",
					"fcHover":"599fcf",
					"borderColorActive":"999999",
					"bgColorActive":"999999",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffffff",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"444444",
					"borderColorError":"c0402a",
					"bgColorError":"c0402a",
					"fcError":"ffffff",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"3383bb",
					"fcAnchorVisited":"b68bba",
					"fcAnchorHover":"175887",

					"bgColorContent2":"d4d4d4",
					"fcContent2":"616161",
					"fcTime":"7f3e7f",
					"fcQuote":"005ea1"
				},

				"Le Frog": {
					"cornerRadius":"10px",
					"borderColorHeader":"3f7506",
					"bgColorHeader":"3a8104",
					"fcHeader":"ffffff",
					"borderColorContent":"72b42d",
					"bgColorContent":"285c00",
					"fcContent":"ffffff",
					"borderColorDefault":"45930b",
					"bgColorDefault":"4ca20b",
					"fcDefault":"ffffff",
					"borderColorHover":"8bd83b",
					"bgColorHover":"4eb305",
					"fcHover":"ffffff",
					"borderColorActive":"72b42d",
					"bgColorActive":"285c00",
					"fcActive":"ffffff",
					"borderColorHighlight":"f9dd34",
					"bgColorHighlight":"fbf5d0",
					"fcHighlight":"363636",
					"borderColorError":"fad000",
					"bgColorError":"ffdc2e",
					"fcError":"2b2b2b",
					"bgColorOverlay":"444444",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"cfffdf",
					"fcAnchorVisited":"9bcfac",
					"fcAnchorHover":"93cf68",

					"bgColorContent2":"2b6300",
					"fcContent2":"a7c2d1",
					"fcTime":"c1c46e",
					"fcQuote":"67b8e0"
				},

				"Flick": {
					"cornerRadius":"2px",
					"borderColorHeader":"dddddd",
					"bgColorHeader":"dddddd",
					"fcHeader":"444444",
					"borderColorContent":"dddddd",
					"bgColorContent":"ffffff",
					"fcContent":"444444",
					"borderColorDefault":"dddddd",
					"bgColorDefault":"f6f6f6",
					"fcDefault":"0073ea",
					"borderColorHover":"0073ea",
					"bgColorHover":"0073ea",
					"fcHover":"ffffff",
					"borderColorActive":"dddddd",
					"bgColorActive":"ffffff",
					"fcActive":"ff0084",
					"borderColorHighlight":"cccccc",
					"bgColorHighlight":"ffffff",
					"fcHighlight":"444444",
					"borderColorError":"ff0084",
					"bgColorError":"ffffff",
					"fcError":"222222",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"0073ea",
					"fcAnchorVisited":"963beb",
					"fcAnchorHover":"0055b0",

					"bgColorContent2":"eeeeee",
					"fcContent2":"999999",
					"fcTime":"c2779c",
					"fcQuote":"204396"
				},

				"Pepper Grinder": {
					"cornerRadius":"6px",
					"borderColorHeader":"d4d1bf",
					"bgColorHeader":"ffffff",
					"fcHeader":"453821",
					"borderColorContent":"d9d6c4",
					"bgColorContent":"eceadf",
					"fcContent":"1f1f1f",
					"borderColorDefault":"cbc7bd",
					"bgColorDefault":"f8f7f6",
					"fcDefault":"654b24",
					"borderColorHover":"654b24",
					"bgColorHover":"654b24",
					"fcHover":"ffffff",
					"borderColorActive":"d9d6c4",
					"bgColorActive":"eceadf",
					"fcActive":"140f06",
					"borderColorHighlight":"b2a266",
					"bgColorHighlight":"f7f3de",
					"fcHighlight":"3a3427",
					"borderColorError":"681818",
					"bgColorError":"b83400",
					"fcError":"ffffff",
					"bgColorOverlay":"6e4f1c",
					"bgColorShadow":"000000",

					"fcAnchorLink":"654b24",
					"fcAnchorVisited":"997237",
					"fcAnchorHover":"7d6136",

					"bgColorContent2":"e0ded3",
					"fcContent2":"786d5e",
					"fcTime":"808f1f",
					"fcQuote":"c2770e"
				},

				"Eggplant": {
					"cornerRadius":"6px",
					"borderColorHeader":"231d2b",
					"bgColorHeader":"30273a",
					"fcHeader":"ffffff",
					"borderColorContent":"7e7783",
					"bgColorContent":"3d3644",
					"fcContent":"ffffff",
					"borderColorDefault":"dcd9de",
					"bgColorDefault":"dcd9de",
					"fcDefault":"665874",
					"borderColorHover":"d1c5d8",
					"bgColorHover":"eae6ea",
					"fcHover":"734d99",
					"borderColorActive":"7e7783",
					"bgColorActive":"5f5964",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffdb1f",
					"bgColorHighlight":"fafafa",
					"fcHighlight":"333333",
					"borderColorError":"994d53",
					"bgColorError":"994d53",
					"fcError":"ffffff",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"b89fd1",
					"fcAnchorVisited":"8a5eb5",
					"fcAnchorHover":"9c50ab",

					"bgColorContent2":"393240",
					"fcContent2":"675b6e",
					"fcTime":"a13f6b",
					"fcQuote":"7b72db"
				},

				"Dark Hive": {
					"cornerRadius":"6px",
					"borderColorHeader":"333333",
					"bgColorHeader":"444444",
					"fcHeader":"ffffff",
					"borderColorContent":"555555",
					"bgColorContent":"000000",
					"fcContent":"ffffff",
					"borderColorDefault":"444444",
					"bgColorDefault":"222222",
					"fcDefault":"eeeeee",
					"borderColorHover":"0b93d5",
					"bgColorHover":"003147",
					"fcHover":"ffffff",
					"borderColorActive":"26b3f7",
					"bgColorActive":"0972a5",
					"fcActive":"ffffff",
					"borderColorHighlight":"cccccc",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"2e7db2",
					"borderColorError":"ffb73d",
					"bgColorError":"ffc73d",
					"fcError":"111111",
					"bgColorOverlay":"5c5c5c",
					"bgColorShadow":"cccccc",

					"fcAnchorLink":"cfcfcf",
					"fcAnchorVisited":"828282",
					"fcAnchorHover":"0b93d5",

					"bgColorContent2":"121212",
					"fcContent2":"999999",
					"fcTime":"08608c",
					"fcQuote":"0976ad"
				},

				"Cupertino": {
					"cornerRadius":"6px",
					"borderColorHeader":"aed0ea",
					"bgColorHeader":"deedf7",
					"fcHeader":"222222",
					"borderColorContent":"dddddd",
					"bgColorContent":"f2f5f7",
					"fcContent":"362b36",
					"borderColorDefault":"aed0ea",
					"bgColorDefault":"d7ebf9",
					"fcDefault":"2779aa",
					"borderColorHover":"74b2e2",
					"bgColorHover":"e4f1fb",
					"fcHover":"0070a3",
					"borderColorActive":"2694e8",
					"bgColorActive":"3baae3",
					"fcActive":"ffffff",
					"borderColorHighlight":"f9dd34",
					"bgColorHighlight":"ffef8f",
					"fcHighlight":"363636",
					"borderColorError":"cd0a0a",
					"bgColorError":"cd0a0a",
					"fcError":"ffffff",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"000000",

					"fcAnchorLink":"2779aa",
					"fcAnchorVisited":"4b70ab",
					"fcAnchorHover":"3baae3",

					"bgColorContent2":"edf0f2",
					"fcContent2":"818da1",
					"fcTime":"77a5d4",
					"fcQuote":"3f63a1"
				},

				"South Street": {
					"cornerRadius":"6px",
					"borderColorHeader":"d4ccb0",
					"bgColorHeader":"ece8da",
					"fcHeader":"433f38",
					"borderColorContent":"dfd9c3",
					"bgColorContent":"f5f3e5",
					"fcContent":"312e25",
					"borderColorDefault":"327E04",
					"bgColorDefault":"459e00",
					"fcDefault":"ffffff",
					"borderColorHover":"327E04",
					"bgColorHover":"67b021",
					"fcHover":"ffffff",
					"borderColorActive":"d4ccb0",
					"bgColorActive":"fafaf4",
					"fcActive":"459e00",
					"borderColorHighlight":"e8e1b5",
					"bgColorHighlight":"fcf0ba",
					"fcHighlight":"363636",
					"borderColorError":"e3a345",
					"bgColorError":"ffedad",
					"fcError":"cd5c0a",
					"bgColorOverlay":"2b2922",
					"bgColorShadow":"cccccc",

					"fcAnchorLink":"459e00",
					"fcAnchorVisited":"388200",
					"fcAnchorHover":"67b021",

					"bgColorContent2":"f0eedf",
					"fcContent2":"d4ccb0",
					"fcTime":"858300",
					"fcQuote":"499447"
				},

				"Blitzer": {
					"cornerRadius":"6px",
					"borderColorHeader":"e3a1a1",
					"bgColorHeader":"cc0000",
					"fcHeader":"ffffff",
					"borderColorContent":"eeeeee",
					"bgColorContent":"ffffff",
					"fcContent":"333333",
					"borderColorDefault":"d8dcdf",
					"bgColorDefault":"eeeeee",
					"fcDefault":"004276",
					"borderColorHover":"cdd5da",
					"bgColorHover":"f6f6f6",
					"fcHover":"111111",
					"borderColorActive":"eeeeee",
					"bgColorActive":"ffffff",
					"fcActive":"cc0000",
					"borderColorHighlight":"fcd3a1",
					"bgColorHighlight":"fbf8ee",
					"fcHighlight":"444444",
					"borderColorError":"cc0000",
					"bgColorError":"f3d8d8",
					"fcError":"2e2e2e",
					"bgColorOverlay":"a6a6a6",
					"bgColorShadow":"333333",

					"fcAnchorLink":"004276",
					"fcAnchorVisited":"313678",
					"fcAnchorHover":"000000",

					"bgColorContent2":"f2f2f2",
					"fcContent2":"838599",
					"fcTime":"8c8334",
					"fcQuote":"0f0f57"
				},

				"Humanity": {
					"cornerRadius":"6px",
					"borderColorHeader":"d49768",
					"bgColorHeader":"cb842e",
					"fcHeader":"ffffff",
					"borderColorContent":"e0cfc2",
					"bgColorContent":"f4f0ec",
					"fcContent":"1e1b1d",
					"borderColorDefault":"cdc3b7",
					"bgColorDefault":"ede4d4",
					"fcDefault":"3f3731",
					"borderColorHover":"f5ad66",
					"bgColorHover":"f5f0e5",
					"fcHover":"a46313",
					"borderColorActive":"e0cfc2",
					"bgColorActive":"f4f0ec",
					"fcActive":"b85700",
					"borderColorHighlight":"d9bb73",
					"bgColorHighlight":"f5f5b5",
					"fcHighlight":"060200",
					"borderColorError":"f8893f",
					"bgColorError":"fee4bd",
					"fcError":"592003",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"3f3731",
					"fcAnchorVisited":"73614e",
					"fcAnchorHover":"a46313",

					"bgColorContent2":"f0ece8",
					"fcContent2":"7f756c",
					"fcTime":"8f452b",
					"fcQuote":"612f07"
				},

				"Hot Sneaks": {
					"cornerRadius":"4px",
					"borderColorHeader":"2c4359",
					"bgColorHeader":"35414f",
					"fcHeader":"e1e463",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"ffffff",
					"fcContent":"2c4359",
					"borderColorDefault":"93c3cd",
					"bgColorDefault":"93c3cd",
					"fcDefault":"333333",
					"borderColorHover":"999999",
					"bgColorHover":"ccd232",
					"fcHover":"212121",
					"borderColorActive":"ff6b7f",
					"bgColorActive":"db4865",
					"fcActive":"ffffff",
					"borderColorHighlight":"b4d100",
					"bgColorHighlight":"ffff38",
					"fcHighlight":"363636",
					"borderColorError":"ff6b7f",
					"bgColorError":"ff3853",
					"fcError":"ffffff",
					"bgColorOverlay":"f7f7ba",
					"bgColorShadow":"ba9217",

					"fcAnchorLink":"333333",
					"fcAnchorVisited":"577278",
					"fcAnchorHover":"db4865",

					"bgColorContent2":"e6f0f2",
					"fcContent2":"748487",
					"fcTime":"b04c60",
					"fcQuote":"3e7b87"
				},

				"Excite Bike": {
					"cornerRadius":"3px",
					"borderColorHeader":"cccccc",
					"bgColorHeader":"f9f9f9",
					"fcHeader":"e69700",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"eeeeee",
					"fcContent":"222222",
					"borderColorDefault":"ffffff",
					"bgColorDefault":"1484e6",
					"fcDefault":"ffffff",
					"borderColorHover":"2293f7",
					"bgColorHover":"2293f7",
					"fcHover":"ffffff",
					"borderColorActive":"e69700",
					"bgColorActive":"e69700",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffffff",
					"bgColorHighlight":"c5ddfc",
					"fcHighlight":"333333",
					"borderColorError":"e69700",
					"bgColorError":"e69700",
					"fcError":"ffffff",
					"bgColorOverlay":"e6b900",
					"bgColorShadow":"e69700",

					"fcAnchorLink":"1484e6",
					"fcAnchorVisited":"e69700",
					"fcAnchorHover":"3772a6",

					"bgColorContent2":"e8e8e8",
					"fcContent2":"877f71",
					"fcTime":"e69700",
					"fcQuote":"116ab8"
				},

				"Vader": {
					"cornerRadius":"3px",
					"borderColorHeader":"404040",
					"bgColorHeader":"888888",
					"fcHeader":"ffffff",
					"borderColorContent":"404040",
					"bgColorContent":"121212",
					"fcContent":"eeeeee",
					"borderColorDefault":"cccccc",
					"bgColorDefault":"adadad",
					"fcDefault":"333333",
					"borderColorHover":"dddddd",
					"bgColorHover":"dddddd",
					"fcHover":"000000",
					"borderColorActive":"000000",
					"bgColorActive":"121212",
					"fcActive":"ffffff",
					"borderColorHighlight":"404040",
					"bgColorHighlight":"555555",
					"fcHighlight":"cccccc",
					"borderColorError":"cd0a0a",
					"bgColorError":"fef1ec",
					"fcError":"cd0a0a",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"adadad",
					"fcAnchorVisited":"7a7a7a",
					"fcAnchorHover":"dddddd",

					"bgColorContent2":"141414",
					"fcContent2":"7f7f7f",
					"fcTime":"666666",
					"fcQuote":"b0b0b0"
				},

				"Dot Luv": {
					"cornerRadius":"4px",
					"borderColorHeader":"0b3e6f",
					"bgColorHeader":"0b3e6f",
					"fcHeader":"f6f6f6",
					"borderColorContent":"000000",
					"bgColorContent":"111111",
					"fcContent":"d9d9d9",
					"borderColorDefault":"333333",
					"bgColorDefault":"333333",
					"fcDefault":"ffffff",
					"borderColorHover":"222222",
					"bgColorHover":"00498f",
					"fcHover":"ffffff",
					"borderColorActive":"096ac8",
					"bgColorActive":"292929",
					"fcActive":"75abff",
					"borderColorHighlight":"052f57",
					"bgColorHighlight":"0b58a2",
					"fcHighlight":"ffffff",
					"borderColorError":"cd0a0a",
					"bgColorError":"a32d00",
					"fcError":"ffffff",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"d9d9d9",
					"fcAnchorVisited":"6f789d",
					"fcAnchorHover":"75abff",

					"bgColorContent2":"171717",
					"fcContent2":"677387",
					"fcTime":"00498f",
					"fcQuote":"85a5d9"
				},

				"Mint Choc": {
					"cornerRadius":"4px",
					"borderColorHeader":"695649",
					"bgColorHeader":"453326",
					"fcHeader":"e3ddc9",
					"borderColorContent":"9c947c",
					"bgColorContent":"201913",
					"fcContent":"ffffff",
					"borderColorDefault":"695444",
					"bgColorDefault":"1c160d",
					"fcDefault":"9bcc60",
					"borderColorHover":"9c947c",
					"bgColorHover":"44372c",
					"fcHover":"baec7e",
					"borderColorActive":"9c947c",
					"bgColorActive":"201913",
					"fcActive":"e3ddc9",
					"borderColorHighlight":"add978",
					"bgColorHighlight":"619226",
					"fcHighlight":"ffffff",
					"borderColorError":"5f391b",
					"bgColorError":"5f391b",
					"fcError":"ffffff",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"9bcc60",
					"fcAnchorVisited":"6e9144",
					"fcAnchorHover":"baec7e",

					"bgColorContent2":"261e16",
					"fcContent2":"79856a",
					"fcTime":"9bcc60",
					"fcQuote":"9bcc60"
				},

				"Black Tie": {
					"cornerRadius":"4px",
					"borderColorHeader":"a3a3a3",
					"bgColorHeader":"333333",
					"fcHeader":"eeeeee",
					"borderColorContent":"cccccc",
					"bgColorContent":"f9f9f9",
					"fcContent":"222222",
					"borderColorDefault":"777777",
					"bgColorDefault":"111111",
					"fcDefault":"e3e3e3",
					"borderColorHover":"000000",
					"bgColorHover":"1c1c1c",
					"fcHover":"ffffff",
					"borderColorActive":"cccccc",
					"bgColorActive":"ffffff",
					"fcActive":"222222",
					"borderColorHighlight":"ffde2e",
					"bgColorHighlight":"ffeb80",
					"fcHighlight":"363636",
					"borderColorError":"9e0505",
					"bgColorError":"cd0a0a",
					"fcError":"ffffff",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa",

					"fcAnchorLink":"111111",
					"fcAnchorVisited":"545454",
					"fcAnchorHover":"999999",

					"bgColorContent2":"f2f2f2",
					"fcContent2":"a1a1a1",
					"fcTime":"a19551",
					"fcQuote":"363636"
				},

				"Trontastic": {
					"cornerRadius":"6px",
					"borderColorHeader":"000000",
					"bgColorHeader":"9fda58",
					"fcHeader":"222222",
					"borderColorContent":"4a4a4a",
					"bgColorContent":"000000",
					"fcContent":"ffffff",
					"borderColorDefault":"1b1613",
					"bgColorDefault":"0a0a0a",
					"fcDefault":"b8ec79",
					"borderColorHover":"000000",
					"bgColorHover":"000000",
					"fcHover":"96f226",
					"borderColorActive":"696969",
					"bgColorActive":"4c4c4c",
					"fcActive":"ffffff",
					"borderColorHighlight":"8cce3b",
					"bgColorHighlight":"f1fbe5",
					"fcHighlight":"030303",
					"borderColorError":"f1ac88",
					"bgColorError":"f6ecd5",
					"fcError":"74736d",
					"bgColorOverlay":"262626",
					"bgColorShadow":"303030",

					"fcAnchorLink":"b8ec79",
					"fcAnchorVisited":"8cb35b",
					"fcAnchorHover":"96f226",

					"bgColorContent2":"1a1a1a",
					"fcContent2":"69755a",
					"fcTime":"b8ec79",
					"fcQuote":"5f9919"
				},

				"Swansky Purse": {
					"cornerRadius":"5px",
					"borderColorHeader":"baaa5a",
					"bgColorHeader":"261803",
					"fcHeader":"eacd86",
					"borderColorContent":"efec9f",
					"bgColorContent":"443113",
					"fcContent":"efec9f",
					"borderColorDefault":"362917",
					"bgColorDefault":"4f4221",
					"fcDefault":"f8eec9",
					"borderColorHover":"362917",
					"bgColorHover":"675423",
					"fcHover":"f8eec9",
					"borderColorActive":"efec9f",
					"bgColorActive":"443113",
					"fcActive":"f9f2bd",
					"borderColorHighlight":"362917",
					"bgColorHighlight":"d5ac5d",
					"fcHighlight":"060200",
					"borderColorError":"c26629",
					"bgColorError":"fee4bd",
					"fcError":"803f1e",
					"bgColorOverlay":"372806",
					"bgColorShadow":"ddd4b0",

					"fcAnchorLink":"f8eec9",
					"fcAnchorVisited":"ada68c",
					"fcAnchorHover":"5e5a4c",

					"bgColorContent2":"4a3615",
					"fcContent2":"7d7452",
					"fcTime":"f8eec9",
					"fcQuote":"8c753b"
				}
			}
		}
	}
}

});
