annuus.addModules(function(){ return {

'f42d2599-ae79-40de-a3a2-9016097454f4':
{
	title: 'Themes',
	pages: { comp: [all] },
	tasks: {
		'd15b72b1': {
			type: 'resource',
			title: 'themes',
			resource: {
				"HKGolden": {
					"cornerRadius":"0px",
					"borderColorHeader":"6ea0c4",
					"bgColorHeader":"6ea0c4",
					"fcHeader":"ffffff",
					"borderColorContent":"cccccc",
					"bgColorContent":"ffffff",
					"fcContent":"000000",
					"borderColorDefault":"ccddea",
					"bgColorDefault":"ccddea",
					"fcDefault":"1a3448",
					"borderColorHover":"ccddea",
					"bgColorHover":"ccddea",
					"fcHover":"33aaaa",
					"borderColorActive":"ccddea",
					"bgColorActive":"ccddea",
					"fcActive":"33aaaa",
					"borderColorHighlight":"ffffff",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"444444",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa"
				},

				"HKGolden 2": {
					"cornerRadius":"0px",
					"borderColorHeader":"6ea0c4",
					"bgColorHeader":"6ea0c4",
					"fcHeader":"ffffff",
					"borderColorContent":"cccccc",
					"bgColorContent":"ffffff",
					"fcContent":"000000",
					"borderColorDefault":"c0c0c0",
					"bgColorDefault":"ffffff",
					"fcDefault":"336699",
					"borderColorHover":"99bbee",
					"bgColorHover":"99bbee",
					"fcHover":"ffffff",
					"borderColorActive":"99bbee",
					"bgColorActive":"99bbee",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffffff",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"444444",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa"
				},

				"UI Lightness": {
					"cornerRadius":"4px",
					"borderColorHeader":"e78f08",
					"bgColorHeader":"f6a828",
					"fcHeader":"ffffff",
					"borderColorContent":"dddddd",
					"bgColorContent":"eeeeee",
					"fcContent":"333333",
					"borderColorDefault":"cccccc",
					"bgColorDefault":"f6f6f6",
					"fcDefault":"1c94c4",
					"borderColorHover":"fbcb09",
					"bgColorHover":"fdf5ce",
					"fcHover":"c77405",
					"borderColorActive":"fbd850",
					"bgColorActive":"ffffff",
					"fcActive":"eb8f00",
					"borderColorHighlight":"fed22f",
					"bgColorHighlight":"ffe45c",
					"fcHighlight":"363636",
					"bgColorOverlay":"666666",
					"bgColorShadow":"000000"
				},

				"UI Darkness": {
					"cornerRadius":"6px",
					"borderColorHeader":"333333",
					"bgColorHeader":"333333",
					"fcHeader":"ffffff",
					"borderColorContent":"666666",
					"bgColorContent":"000000",
					"fcContent":"ffffff",
					"borderColorDefault":"666666",
					"bgColorDefault":"555555",
					"fcDefault":"eeeeee",
					"borderColorHover":"59b4d4",
					"bgColorHover":"0078a3",
					"fcHover":"ffffff",
					"borderColorActive":"ffaf0f",
					"bgColorActive":"f58400",
					"fcActive":"ffffff",
					"borderColorHighlight":"cccccc",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"2e7db2",
					"bgColorOverlay":"5c5c5c",
					"bgColorShadow":"cccccc"
				},

				"Smoothness": {
					"cornerRadius":"4px",
					"borderColorHeader":"aaaaaa",
					"bgColorHeader":"cccccc",
					"fcHeader":"222222",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"ffffff",
					"fcContent":"222222",
					"borderColorDefault":"d3d3d3",
					"bgColorDefault":"e6e6e6",
					"fcDefault":"555555",
					"borderColorHover":"999999",
					"bgColorHover":"dadada",
					"fcHover":"212121",
					"borderColorActive":"aaaaaa",
					"bgColorActive":"ffffff",
					"fcActive":"212121",
					"borderColorHighlight":"fcefa1",
					"bgColorHighlight":"fbf9ee",
					"fcHighlight":"363636",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Start": {
					"cornerRadius":"5px",
					"borderColorHeader":"4297d7",
					"bgColorHeader":"2191c0",
					"fcHeader":"eaf5f7",
					"borderColorContent":"a6c9e2",
					"bgColorContent":"fcfdfd",
					"fcContent":"222222",
					"borderColorDefault":"77d5f7",
					"bgColorDefault":"0078ae",
					"fcDefault":"ffffff",
					"borderColorHover":"448dae",
					"bgColorHover":"79c9ec",
					"fcHover":"026890",
					"borderColorActive":"acdd4a",
					"bgColorActive":"6eac2c",
					"fcActive":"ffffff",
					"borderColorHighlight":"fcd113",
					"bgColorHighlight":"f8da4e",
					"fcHighlight":"915608",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"999999"
				},

				"Redmond": {
					"cornerRadius":"5px",
					"borderColorHeader":"4297d7",
					"bgColorHeader":"5c9ccc",
					"fcHeader":"ffffff",
					"borderColorContent":"a6c9e2",
					"bgColorContent":"fcfdfd",
					"fcContent":"222222",
					"borderColorDefault":"c5dbec",
					"bgColorDefault":"dfeffc",
					"fcDefault":"2e6e9e",
					"borderColorHover":"79b7e7",
					"bgColorHover":"d0e5f5",
					"fcHover":"1d5987",
					"borderColorActive":"79b7e7",
					"bgColorActive":"f5f8f9",
					"fcActive":"e17009",
					"borderColorHighlight":"fad42e",
					"bgColorHighlight":"fbec88",
					"fcHighlight":"363636",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Sunny": {
					"cornerRadius":"5px",
					"borderColorHeader":"4297d7",
					"bgColorHeader":"5c9ccc",
					"fcHeader":"ffffff",
					"borderColorContent":"a6c9e2",
					"bgColorContent":"fcfdfd",
					"fcContent":"222222",
					"borderColorDefault":"c5dbec",
					"bgColorDefault":"dfeffc",
					"fcDefault":"2e6e9e",
					"borderColorHover":"79b7e7",
					"bgColorHover":"d0e5f5",
					"fcHover":"1d5987",
					"borderColorActive":"79b7e7",
					"bgColorActive":"f5f8f9",
					"fcActive":"e17009",
					"borderColorHighlight":"fad42e",
					"bgColorHighlight":"fbec88",
					"fcHighlight":"363636",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Overcast": {
					"cornerRadius":"6px",
					"borderColorHeader":"bbbbbb",
					"bgColorHeader":"dddddd",
					"fcHeader":"444444",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"c9c9c9",
					"fcContent":"333333",
					"borderColorDefault":"cccccc",
					"bgColorDefault":"eeeeee",
					"fcDefault":"3383bb",
					"borderColorHover":"bbbbbb",
					"bgColorHover":"f8f8f8",
					"fcHover":"599fcf",
					"borderColorActive":"999999",
					"bgColorActive":"999999",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffffff",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"444444",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa"
				},

				"Le Frog": {
					"cornerRadius":"10px",
					"borderColorHeader":"3f7506",
					"bgColorHeader":"3a8104",
					"fcHeader":"ffffff",
					"borderColorContent":"72b42d",
					"bgColorContent":"285c00",
					"fcContent":"ffffff",
					"borderColorDefault":"45930b",
					"bgColorDefault":"4ca20b",
					"fcDefault":"ffffff",
					"borderColorHover":"8bd83b",
					"bgColorHover":"4eb305",
					"fcHover":"ffffff",
					"borderColorActive":"72b42d",
					"bgColorActive":"285c00",
					"fcActive":"ffffff",
					"borderColorHighlight":"f9dd34",
					"bgColorHighlight":"fbf5d0",
					"fcHighlight":"363636",
					"bgColorOverlay":"444444",
					"bgColorShadow":"aaaaaa"
				},

				"Flick": {
					"cornerRadius":"2px",
					"borderColorHeader":"dddddd",
					"bgColorHeader":"dddddd",
					"fcHeader":"444444",
					"borderColorContent":"dddddd",
					"bgColorContent":"ffffff",
					"fcContent":"444444",
					"borderColorDefault":"dddddd",
					"bgColorDefault":"f6f6f6",
					"fcDefault":"0073ea",
					"borderColorHover":"0073ea",
					"bgColorHover":"0073ea",
					"fcHover":"ffffff",
					"borderColorActive":"dddddd",
					"bgColorActive":"ffffff",
					"fcActive":"ff0084",
					"borderColorHighlight":"cccccc",
					"bgColorHighlight":"ffffff",
					"fcHighlight":"444444",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa"
				},

				"Pepper Grinder": {
					"cornerRadius":"6px",
					"borderColorHeader":"d4d1bf",
					"bgColorHeader":"ffffff",
					"fcHeader":"453821",
					"borderColorContent":"d9d6c4",
					"bgColorContent":"eceadf",
					"fcContent":"1f1f1f",
					"borderColorDefault":"cbc7bd",
					"bgColorDefault":"f8f7f6",
					"fcDefault":"654b24",
					"borderColorHover":"654b24",
					"bgColorHover":"654b24",
					"fcHover":"ffffff",
					"borderColorActive":"d9d6c4",
					"bgColorActive":"eceadf",
					"fcActive":"140f06",
					"borderColorHighlight":"b2a266",
					"bgColorHighlight":"f7f3de",
					"fcHighlight":"3a3427",
					"bgColorOverlay":"6e4f1c",
					"bgColorShadow":"000000"
				},

				"Eggplant": {
					"cornerRadius":"6px",
					"borderColorHeader":"231d2b",
					"bgColorHeader":"30273a",
					"fcHeader":"ffffff",
					"borderColorContent":"7e7783",
					"bgColorContent":"3d3644",
					"fcContent":"ffffff",
					"borderColorDefault":"dcd9de",
					"bgColorDefault":"dcd9de",
					"fcDefault":"665874",
					"borderColorHover":"d1c5d8",
					"bgColorHover":"eae6ea",
					"fcHover":"734d99",
					"borderColorActive":"7e7783",
					"bgColorActive":"5f5964",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffdb1f",
					"bgColorHighlight":"fafafa",
					"fcHighlight":"333333",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"aaaaaa"
				},

				"Dark Hive": {
					"cornerRadius":"6px",
					"borderColorHeader":"333333",
					"bgColorHeader":"444444",
					"fcHeader":"ffffff",
					"borderColorContent":"555555",
					"bgColorContent":"000000",
					"fcContent":"ffffff",
					"borderColorDefault":"444444",
					"bgColorDefault":"222222",
					"fcDefault":"eeeeee",
					"borderColorHover":"0b93d5",
					"bgColorHover":"003147",
					"fcHover":"ffffff",
					"borderColorActive":"26b3f7",
					"bgColorActive":"0972a5",
					"fcActive":"ffffff",
					"borderColorHighlight":"cccccc",
					"bgColorHighlight":"eeeeee",
					"fcHighlight":"2e7db2",
					"bgColorOverlay":"5c5c5c",
					"bgColorShadow":"cccccc"
				},

				"Cupertino": {
					"cornerRadius":"6px",
					"borderColorHeader":"aed0ea",
					"bgColorHeader":"deedf7",
					"fcHeader":"222222",
					"borderColorContent":"dddddd",
					"bgColorContent":"f2f5f7",
					"fcContent":"362b36",
					"borderColorDefault":"aed0ea",
					"bgColorDefault":"d7ebf9",
					"fcDefault":"2779aa",
					"borderColorHover":"74b2e2",
					"bgColorHover":"e4f1fb",
					"fcHover":"0070a3",
					"borderColorActive":"2694e8",
					"bgColorActive":"3baae3",
					"fcActive":"ffffff",
					"borderColorHighlight":"f9dd34",
					"bgColorHighlight":"ffef8f",
					"fcHighlight":"363636",
					"bgColorOverlay":"eeeeee",
					"bgColorShadow":"000000"
				},

				"South Street": {
					"cornerRadius":"6px",
					"borderColorHeader":"d4ccb0",
					"bgColorHeader":"ece8da",
					"fcHeader":"433f38",
					"borderColorContent":"dfd9c3",
					"bgColorContent":"f5f3e5",
					"fcContent":"312e25",
					"borderColorDefault":"327E04",
					"bgColorDefault":"459e00",
					"fcDefault":"ffffff",
					"borderColorHover":"327E04",
					"bgColorHover":"67b021",
					"fcHover":"ffffff",
					"borderColorActive":"d4ccb0",
					"bgColorActive":"fafaf4",
					"fcActive":"459e00",
					"borderColorHighlight":"e8e1b5",
					"bgColorHighlight":"fcf0ba",
					"fcHighlight":"363636",
					"bgColorOverlay":"2b2922",
					"bgColorShadow":"cccccc"
				},

				"Blitzer": {
					"cornerRadius":"6px",
					"borderColorHeader":"e3a1a1",
					"bgColorHeader":"cc0000",
					"fcHeader":"ffffff",
					"borderColorContent":"eeeeee",
					"bgColorContent":"ffffff",
					"fcContent":"333333",
					"borderColorDefault":"d8dcdf",
					"bgColorDefault":"eeeeee",
					"fcDefault":"004276",
					"borderColorHover":"cdd5da",
					"bgColorHover":"f6f6f6",
					"fcHover":"111111",
					"borderColorActive":"eeeeee",
					"bgColorActive":"ffffff",
					"fcActive":"cc0000",
					"borderColorHighlight":"fcd3a1",
					"bgColorHighlight":"fbf8ee",
					"fcHighlight":"444444",
					"bgColorOverlay":"a6a6a6",
					"bgColorShadow":"333333"
				},

				"Humanity": {
					"cornerRadius":"6px",
					"borderColorHeader":"d49768",
					"bgColorHeader":"cb842e",
					"fcHeader":"ffffff",
					"borderColorContent":"e0cfc2",
					"bgColorContent":"f4f0ec",
					"fcContent":"1e1b1d",
					"borderColorDefault":"cdc3b7",
					"bgColorDefault":"ede4d4",
					"fcDefault":"3f3731",
					"borderColorHover":"f5ad66",
					"bgColorHover":"f5f0e5",
					"fcHover":"a46313",
					"borderColorActive":"e0cfc2",
					"bgColorActive":"f4f0ec",
					"fcActive":"b85700",
					"borderColorHighlight":"d9bb73",
					"bgColorHighlight":"f5f5b5",
					"fcHighlight":"060200",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Hot Sneaks": {
					"cornerRadius":"4px",
					"borderColorHeader":"2c4359",
					"bgColorHeader":"35414f",
					"fcHeader":"e1e463",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"ffffff",
					"fcContent":"2c4359",
					"borderColorDefault":"93c3cd",
					"bgColorDefault":"93c3cd",
					"fcDefault":"333333",
					"borderColorHover":"999999",
					"bgColorHover":"ccd232",
					"fcHover":"212121",
					"borderColorActive":"ff6b7f",
					"bgColorActive":"db4865",
					"fcActive":"ffffff",
					"borderColorHighlight":"b4d100",
					"bgColorHighlight":"ffff38",
					"fcHighlight":"363636",
					"bgColorOverlay":"f7f7ba",
					"bgColorShadow":"ba9217"
				},

				"Excite Bike": {
					"cornerRadius":"3px",
					"borderColorHeader":"cccccc",
					"bgColorHeader":"f9f9f9",
					"fcHeader":"e69700",
					"borderColorContent":"aaaaaa",
					"bgColorContent":"eeeeee",
					"fcContent":"222222",
					"borderColorDefault":"ffffff",
					"bgColorDefault":"1484e6",
					"fcDefault":"ffffff",
					"borderColorHover":"2293f7",
					"bgColorHover":"2293f7",
					"fcHover":"ffffff",
					"borderColorActive":"e69700",
					"bgColorActive":"e69700",
					"fcActive":"ffffff",
					"borderColorHighlight":"ffffff",
					"bgColorHighlight":"c5ddfc",
					"fcHighlight":"333333",
					"bgColorOverlay":"e6b900",
					"bgColorShadow":"e69700"
				},

				"Vader": {
					"cornerRadius":"4px",
					"borderColorHeader":"e78f08",
					"bgColorHeader":"f6a828",
					"fcHeader":"ffffff",
					"borderColorContent":"dddddd",
					"bgColorContent":"eeeeee",
					"fcContent":"333333",
					"borderColorDefault":"cccccc",
					"bgColorDefault":"f6f6f6",
					"fcDefault":"1c94c4",
					"borderColorHover":"fbcb09",
					"bgColorHover":"fdf5ce",
					"fcHover":"c77405",
					"borderColorActive":"fbd850",
					"bgColorActive":"ffffff",
					"fcActive":"eb8f00",
					"borderColorHighlight":"fed22f",
					"bgColorHighlight":"ffe45c",
					"fcHighlight":"363636",
					"bgColorOverlay":"666666",
					"bgColorShadow":"000000"
				},

				"Dot Luv": {
					"cornerRadius":"4px",
					"borderColorHeader":"0b3e6f",
					"bgColorHeader":"0b3e6f",
					"fcHeader":"f6f6f6",
					"borderColorContent":"000000",
					"bgColorContent":"111111",
					"fcContent":"d9d9d9",
					"borderColorDefault":"333333",
					"bgColorDefault":"333333",
					"fcDefault":"ffffff",
					"borderColorHover":"222222",
					"bgColorHover":"00498f",
					"fcHover":"ffffff",
					"borderColorActive":"096ac8",
					"bgColorActive":"292929",
					"fcActive":"75abff",
					"borderColorHighlight":"052f57",
					"bgColorHighlight":"0b58a2",
					"fcHighlight":"ffffff",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Mint Choc": {
					"cornerRadius":"4px",
					"borderColorHeader":"695649",
					"bgColorHeader":"453326",
					"fcHeader":"e3ddc9",
					"borderColorContent":"9c947c",
					"bgColorContent":"201913",
					"fcContent":"ffffff",
					"borderColorDefault":"695444",
					"bgColorDefault":"1c160d",
					"fcDefault":"9bcc60",
					"borderColorHover":"9c947c",
					"bgColorHover":"44372c",
					"fcHover":"baec7e",
					"borderColorActive":"9c947c",
					"bgColorActive":"201913",
					"fcActive":"e3ddc9",
					"borderColorHighlight":"add978",
					"bgColorHighlight":"619226",
					"fcHighlight":"ffffff",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Black Tie": {
					"cornerRadius":"4px",
					"borderColorHeader":"a3a3a3",
					"bgColorHeader":"333333",
					"fcHeader":"eeeeee",
					"borderColorContent":"cccccc",
					"bgColorContent":"f9f9f9",
					"fcContent":"222222",
					"borderColorDefault":"777777",
					"bgColorDefault":"111111",
					"fcDefault":"e3e3e3",
					"borderColorHover":"000000",
					"bgColorHover":"1c1c1c",
					"fcHover":"ffffff",
					"borderColorActive":"cccccc",
					"bgColorActive":"ffffff",
					"fcActive":"222222",
					"borderColorHighlight":"ffde2e",
					"bgColorHighlight":"ffeb80",
					"fcHighlight":"363636",
					"bgColorOverlay":"aaaaaa",
					"bgColorShadow":"aaaaaa"
				},

				"Trontastic": {
					"cornerRadius":"6px",
					"borderColorHeader":"000000",
					"bgColorHeader":"9fda58",
					"fcHeader":"222222",
					"borderColorContent":"4a4a4a",
					"bgColorContent":"000000",
					"fcContent":"ffffff",
					"borderColorDefault":"1b1613",
					"bgColorDefault":"0a0a0a",
					"fcDefault":"b8ec79",
					"borderColorHover":"000000",
					"bgColorHover":"000000",
					"fcHover":"96f226",
					"borderColorActive":"696969",
					"bgColorActive":"4c4c4c",
					"fcActive":"ffffff",
					"borderColorHighlight":"8cce3b",
					"bgColorHighlight":"f1fbe5",
					"fcHighlight":"030303",
					"bgColorOverlay":"262626",
					"bgColorShadow":"303030"
				},

				"Swansky Purse": {
					"cornerRadius":"5px",
					"borderColorHeader":"baaa5a",
					"bgColorHeader":"261803",
					"fcHeader":"eacd86",
					"borderColorContent":"efec9f",
					"bgColorContent":"443113",
					"fcContent":"efec9f",
					"borderColorDefault":"362917",
					"bgColorDefault":"4f4221",
					"fcDefault":"f8eec9",
					"borderColorHover":"362917",
					"bgColorHover":"675423",
					"fcHover":"f8eec9",
					"borderColorActive":"efec9f",
					"bgColorActive":"443113",
					"fcActive":"f9f2bd",
					"borderColorHighlight":"362917",
					"bgColorHighlight":"d5ac5d",
					"fcHighlight":"060200",
					"bgColorOverlay":"372806",
					"bgColorShadow":"ddd4b0"
				}
			}
		}
	}
},

'c878628c-8414-4d1e-9a20-717d1dd0517c': {
	title: 'Theme data extractor',
	pages: { on: [all] },
	tasks: {
		'46ffedd9': {
			run_at: 'document_start',
			ui: ['button'],
			title: 'Theme data extractor',
			css: '\
				#an-extractor { position: fixed; top: 5%; left: 2%; width: 100%; height: 90%; } \
				#an-extractor > textarea { box-sizing: border-box; width: 45%; height: 100%; } \
				#an-extractor > button { width: 5%; height: 100%; vertical-align: bottom; } \
			',
			js: function()
			{
				$('\
					<div id="an-extractor"> \
						<textarea id="an-extractor-input"></textarea> \
							<button>&gt;</button> \
						<textarea id="an-extractor-output"></textarea> \
					</div> \
				')
				.delegate('textarea', 'click', function()
				{
					this.select();
				})
				.appendTo('#an')
				.find('button').click(function()
				{
					var input = $('#an-extractor-input').val();
					var output = {};
					$.each($.themes('HKGolden'), function(name)
					{
						output[name] = input.match($.format('{0}=([^&]+)', name))[1];
					});
					$('#an-extractor-output').val(JSON.stringify(output, null, '\t'));
				});
			}
		}
	}
}

}; });
